#include "CharacterNamePool.h"

const std::vector<char*> CharacterNamePool::m_MaleNames = {
		"Abele", "Abramo", "Achille", "Adalberto", "Adalfieri", "Adamo", "Adolfo",
		"Adone", "Adriano", "Affonso", "Agapeto", "Agapito", "Agostino", "Alberico",
		"Alberto", "Aldo", "Aldobrandino", "Alessio", "Alfeo", "Alfieri", "Alonso",
		"Alphonso", "Alvise", "Amadeo", "Amadore", "Amando", "Amato", "Ambrogino",
		"Amedeo", "Amerigo", "Ampelio", "Anacleto", "Anastasio", "Anatolio", "Andrea",
		"Angelico", "Angelo", "Angioletto", "Angiolo", "Anjelo", "Anselmo", "Antonello",
		"Antonino", "Antonio", "Arcangelo", "Arduino", "Armo", "Arnoldo", "Aroldo",
		"Arrigo", "Arsenio", "Arturo", "Attilio", "Augostino", "Augusto", "Aurelio",
		"Azzo", "Azzolino", "Baldassare", "Baldovino", "Bàrtolo", "Bartolomeo", "Bartolommeo",
		"Basilio", "Battista", "Benedetto", "Beniamino", "Benigno", "Benvenuto", "Beppe",
		"Berengar", "Berengar", "Bernardino", "Bernardo", "Bertoldo", "Bertrando",
		"Bettino", "Biaggio", "Biagino", "Biagio", "Bonaventura", "Bonaventure"
		"Bonfilio", "Bonifacio", "Brizio", "Buonfiglio", "Caj", "Cajetan", "Callisto",
		"Calogero", "Calvino", "Camillo", "Carlo", "Casimiro", "Cecilio", "Celestino",
		"Celino", "Celio", "Celso", "Cesare", "Cesarino", "Cipriano", "Ciriaco",
		"Cirillo", "Cirino", "Ciro", "Claudio", "Clemente", "Cleto", "Colombano",
		"Colombo", "Concetto", "Corrado", "Cosimo", "Costantino", "Costanzo",
		"Crescenzo", "Crispino", "Cristiano", "Cristoforo", "Croccifixio", "Crocifisso",
		"Cross", "Damiano", "Daniele", "Dante", "Dario", "Davide", "Demetrio", "Desi",
		"Desiderio", "Dino", "Domenico", "Donatello", "Donato", "Doriano", "Drago",
		"Duilio", "Durante", "Edmondo","Edoardo", "Efisio", "Egidio", "Elario",
		"Elia", "Eligio", "Eliodoro", "Eliseo", "Elmo", "Elpidio", "Emanuele",
		"Emiliano", "Emilio", "Ennio", "Enrico", "Enzio", "Enzo", "Ercole",
		"Ermanno", "Ermete", "Erminio", "Ernesto", "Estachio", "Ettore", "Eugenio",
		"Eulalio", "Eusebio", "Eustachio", "Eustorgio", "Ezio", "Ezzelin", "Fabiano",
		"Fabio", "Fabrizio", "Faramundo", "Faustino", "Fausto", "Fedele", "Federico",
		"Federigo", "Felice", "Feliciano", "Ferdinando", "Ferro", "Ferruccio", "Filberto",
		"Filiberto", "Filippo", "Filipo", "Fillippo", "Fino", "Fiore", "Fiorello",
		"Fiorenzo", "Firmino", "Flavio", "Florentino", "Floriano", "Fons", "Fonsie",
		"Fortunato", "Francesco", "Franco", "Frediano", "Fredo", "Fulvio", "Gabriele",
		"Gaetano", "Gaspare", "Gasparo", "Gastone", "Gavino", "Gennaro", "Gerardo",
		"Germano", "Gerolamo", "Geronimo", "Gervasio", "Giacinto", "Giacobbe",
		"Giacomo", "Giampiero", "Gianbattista", "Giancarlo", "Gianluca", "Gianluigi",
		"Gianmarco", "Gianmaria", "Gianni", "Giannino", "Gianpaolo", "Gianpiero", "Gino",
		"Gioacchino", "Gioachino", "Giordano", "Giorgio", "Giorgino", "Giosuè",
		"Giovanni", "Giraldo", "Girolamo", "Giuliano", "Giulio", "Giuseppe", "Giustino",
		"Goffredo", "Graziano", "Gregario", "Gualtiero", "Guerino", "Guglielmo",
		"Guido", "Gustavo", "Hieronomo", "Ignazio", "Ilario", "Innocenzo", "Ippolito",
		"Isaia", "Italo", "Jacopo", "Jovanni", "Ladislas", "Lauro", "Lazzaro",
		"Leandro", "Leonardo", "Leone", "Leonzio", "Leopoldo", "Liberatore",
		"Liborio", "Lino", "Livio", "Lodovico", "Lorenzo", "Loris", "Lothario",
		"Lotterio", "Luca", "Luciano", "Lucio", "Ludovico", "Luigi", "Luigino",
		"Macario", "Malvolio" ,"Manfredo", "Malio", "Marcellino", "Marcello",
		"Marco", "Mariano", "Marino", "Mario", "Martino", "Marzio", "Maso",
		"Massimiliano", "Massimo", "Matteo", "Mattia", "Maurizio", "Mauro",
		"Melchiorre", "Meo", "Michelangelo", "Michele", "Modesto", "Mosè", "Naldo",
		"Napoleone", "Narciso", "Natanaele", "Nazario", "Nerio", "Nero", "Nestore",
		"Nevio", "Niccolò", "Nico", "Nicodemo", "Nicola", "Nicolò", "Nicomedo",
		"Nicostrato", "Nino", "Nunzio", "Orazio", "Orfeo", "Orlando", "Orsino",
		"Orso", "Osvaldo", "Ottaviano", "Ottavio", "Ovidio", "Palmiro", "Pancrazio",
		"Panfilo", "Paolo", "Paride", "Pasquale", "Pasqualino", "Patrizio",
		"Pellegrino", "Pepe", "Piero", "Pietro", "Pino", "Pio", "Placido", "Plinio",
		"Poldi", "Pompeo", "Ponzio", "Porfirio", "Primo", "Prospero", "Prudenzio",
		"Quirino", "Raffaaele", "Raffaello", "Raimondo", "Raniero", "Raul",
		"Remigio", "Remo", "Renato", "Renzo", "Riccardo", "Rico", "Rinaldo", "Rino",
		"Roberto", "Rocco", "Rodolfo", "Romano", "Romeo", "Romolo", "Rufino", "Ruggero",
		"Ruggiero", "Sabato", "Sabino", "Salvatore", "Samuele", "Sandro", "Sansone",
		"Santino", "Santo", "Saturnino", "Saverio", "Savino", "Savio", "Scevola",
		"Sebastiano", "Serafino", "Sergio", "Sesto", "Settimio", "Severiano",
		"Severino", "Severo", "Silvano", "Silvestro", "Silvio", "Simone", "Stefano",
		"Tacito", "Taddeo", "Tàmmaro", "Tancredo", "Teobaldo", "Teodoro", "Teodosio",
		"Teofilo", "Terenzio", "Terzo", "Thorello", "Timoteo", "Tino", "Tito",
		"Tiziano", "Tomasso", "Tonio", "Tore", "Uberto", "Udalrico", "Ugo",
		"Ulderico", "Ulisse", "Umberto", "Umfredo", "Urbano", "Valentino",
		"Valeriano", "Valerio", "Vianni", "Vegliantino", "Venceslao", "Vicenzo",
		"Vico", "Vincente", "Vincenzo", "Vinicio", "Virgilio", "Vitale", "Vito",
		"Vittore", "Vittorino", "Vittorio", "Xaviero"
};

const std::vector<char*> CharacterNamePool::m_FemaleNames = {
		"Abelie", "Adalina", "Adelina", "Adona", "Adriana", "Agata", "Agnese",
		"Agostina", "Alba", "Alberta", "Albertina", "Alda", "Alessa", "Alessandra",
		"Alessia", "Alfonsina", "Allegra", "Allegria", "Ambra", "Amedea", "Andreina",
		"Angelica", "Angiola", "Angioletta", "Anjelica", "Annalisa", "Anetta",
		"Anonciada", "Annunciata", "Annunziata", "Antonia", "Antonietta", "Anunciata",
		"Arabella", "Arianna", "Assunta", "Azzurra", "Beatrice", "Benedetta",
		"Benigna", "Bernardetta", "Bertina", "Bettina", "Bianca", "Bibiana", "Bice",
		"Bonfilia", "Brunilda", "Calandra", "Calogera", "Calvina", "Caprice",
		"Capricia", "Carla", "Carlita", "Carlota", "Carlotta", "Caterina",
		"Celestina", "Celia", "Cesarina", "Chiara", "Chiarina", "Cinzia", "Cipriana",
		"Clara", "Coco", "Colombina", "Concetta", "Concettina", "Consolata", "Cosima",
		"Cristiana", "Crocetta", "Crocifissa", "Dafne", "Daniela", "Debora", "Delfina",
		"Desideria", "Detta", "Diamante", "Domenica", "Dona", "Donata", "Donatella",
		"Dorotea", "Drina", "Edda", "Edmonda", "Edvige", "Elda", "Elena", "Eleonora",
		"Elettra", "Elisabetta", "Elma", "Elnora", "Elettra", "Elisabetta", "Elma",
		"Elnora", "Eloisa", "Emiliana", "Enrica", "Enrichetta", "Erminia", "Ernesta",
		"Ersilia", "Eufemia", "Eula", "Eulalia", "Fabrizia", "Federica", "Felìcita",
		"Felisa", "Ferdinanda", "Fiammetta", "Filomena", "Filumena", "Fina",
		"Fioralba", "Fiore", "Fiorella", "Fiorenza", "Florentina", "Floriana",
		"Fortunata", "Franca", "Francesca", "Fulvia", "Gabriella", "Gaetana", "Geltrude",
		"Gemma", "Genevra", "Genoveffa", "Giachetta", "Giacinta", "Giada", "Gianna",
		"Gilda", "Gina", "Ginevra", "Gioconda", "Gioffreda", "Gioia", "Giorgia",
		"Giorgina", "Giosetta", "Giovanna", "Giovanetta", "Gisella", "Giulia",
		"Giuliana", "Giulietta", "Giuseppa", "Giuseppina", "Giustina", "Grazia",
		"Graziana", "Graziella", "Guiditta", "Ilaria", "Imelda", "Immacolata", "Ines",
		"Italia", "Jemma", "Jolanda", "Lalia", "Lauretta", "Leonora", "Letizia", "Lia",
		"Lisa", "Loredana", "Lorenza", "Loreto", "Luciana", "Lucrezia", "Ludovica",
		"Luigia", "Luigina", "Luisa", "Luisella", "Maddalena", "Mafalda", "Malvolia",
		"Marcella", "Margherita", "María", "Mariella", "Marietta", "Marinella", "Marta",
		"Marzia", "Maura", "Melania", "Michela", "Michelangela", "Michelina", "Milana",
		"Mimi", "Mirella", "Mona", "Natale", "Nereza", "Nerezza", "Nerina", "Nicola",
		"Nicoletta", "Nicolina", "Nilda", "Noelia", "Noemi", "Nora", "Norina", "Norma",
		"Nunzia", "Nunziatella", "Nunziatina", "Orabella", "Orlanda", "Ornella", "Orsina",
		"Ottavia", "Palmira", "Paula", "Paolina", "Pasqualina", "Patrizia", "Perla",
		"Perlita", "Petronel", "Petronella", "Piera", "Pierina", "Pietrina", "Pietronella",
		"Pina", "Rachele", "Raffaela", "Raffaella", "Raimonda", "Ravenna", "Renata",
		"Riccarda", "Roberta", "Robertina", "Romana", "Romhilda", "Romilda", "Romola",
		"Rosabella", "Rosalba", "Rosalva", "Rosangela", "Rosanna", "Rosannah", "Rosaria",
		"Rosella", "Rosetta", "Rosina", "Rosella", "Salvatrice", "Samanta", "Samuela",
		"Sandra", "Santa", "Santuzza", "Saveria", "Savina", "Sebastiana", "Selvaggia",
		"Serafina", "Silvana", "Silvia", "Simona", "Simonetta", "Sofia", "Sonia", "Stefania",
		"Susana", "Sylvana", "Tatiana", "Tecla", "Teofila", "Tina", "Tiziana", "Tonia",
		"Valeria", "Vanda", "Vanna", "Velia", "Vincenza", "Violetta", "Vitalia", "Vittoria",
		"Xaviera", "Zeta", "Zita"
};

char* CharacterNamePool::getMaleName()
{
	return m_MaleNames[std::rand() % m_MaleNames.size()];
}

char* CharacterNamePool::getFemaleName()
{
	return m_FemaleNames[std::rand() % m_FemaleNames.size()];
}